services:
  ddvpn-webhook-bot:
    build: .
    container_name: ddvpn-webhook-tgbot
    restart: always
    network_mode: host
    command: python3 -m bot.main
    volumes:
      - /dev/shm:/dev/shm
      - ./bot:/opt/app/bot
    env_file:
      - .env
