remnawave:
  allowed_events:
    # Node
    - node.connection_lost
    - node.connection_restored
    - node.traffic_notify

    # Infra Billing
    - crm.infra_billing_node_payment_in_7_days
    - crm.infra_billing_node_payment_in_48hrs
    - crm.infra_billing_node_payment_in_24hrs
    - crm.infra_billing_node_payment_due_today
    - crm.infra_billing_node_payment_overdue_24hrs
    - crm.infra_billing_node_payment_overdue_48hrs
    - crm.infra_billing_node_payment_overdue_7_days

    # Service
    - service.panel_started
    - service.login_attempt_failed
    - service.login_attempt_success
